### ISSUE TITLE
Bot generation with enabled Level Caps

### ISSUE THREAD

**Issue by ViP3R76** [fryciarz7/HealthPerLevel#13]
[Client Request]  \client\game\bot\generate
[HealthPerLevel] error: TypeError: Cannot read properties of undefined (reading 'Progress')
    at HealthPerLevel.checkPmcHealthSkillLevelCap (/opt/server/user/mods/capatainamnstrfryciarz7-healthperlevel/src/HealthPerLevel.ts:415:45)
    at HealthPerLevel.checkHealthSkillLevelCap (/opt/server/user/mods/capatainamnstrfryciarz7-healthperlevel/src/HealthPerLevel.ts:394:29)
    at HealthPerLevel.calcBotHealth (/opt/server/user/mods/capatainamnstrfryciarz7-healthperlevel/src/HealthPerLevel.ts:492:42)
    at Object.action (/opt/server/user/mods/capatainamnstrfryciarz7-healthperlevel/src/HealthPerLevel.ts:228:54)

**Comment by fryciarz7** [comment]
When did this happen? At the beginning, in the middle or at the end of the raid?
